// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBki-22gJ79Wu_6RNCUb6rXkImI8APFKN4',
    appId: '1:566308976143:web:4e8e16e6bc53089f37d57a',
    messagingSenderId: '566308976143',
    projectId: 'to-do-list-app-270f5',
    authDomain: 'to-do-list-app-270f5.firebaseapp.com',
    storageBucket: 'to-do-list-app-270f5.firebasestorage.app',
    measurementId: 'G-TMMTF51EBH',
    databaseURL: 'https://to-do-list-app-270f5-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpJMVqaTK8yWV4EGNP29VgsiCAUt80pww',
    appId: '1:566308976143:android:1c06311b2d27201d37d57a',
    messagingSenderId: '566308976143',
    projectId: 'to-do-list-app-270f5',
    storageBucket: 'to-do-list-app-270f5.firebasestorage.app',
    databaseURL: 'https://to-do-list-app-270f5-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4vLSzJPTMDh2lfp0c0s6-WFIjwTjpho',
    appId: '1:566308976143:ios:8a2c77229c2f503537d57a',
    messagingSenderId: '566308976143',
    projectId: 'to-do-list-app-270f5',
    storageBucket: 'to-do-list-app-270f5.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
    databaseURL: 'https://to-do-list-app-270f5-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN4vLSzJPTMDh2lfp0c0s6-WFIjwTjpho',
    appId: '1:566308976143:ios:8a2c77229c2f503537d57a',
    messagingSenderId: '566308976143',
    projectId: 'to-do-list-app-270f5',
    storageBucket: 'to-do-list-app-270f5.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
    databaseURL: 'https://to-do-list-app-270f5-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBki-22gJ79Wu_6RNCUb6rXkImI8APFKN4',
    appId: '1:566308976143:web:52cd2969235d284b37d57a',
    messagingSenderId: '566308976143',
    projectId: 'to-do-list-app-270f5',
    authDomain: 'to-do-list-app-270f5.firebaseapp.com',
    storageBucket: 'to-do-list-app-270f5.firebasestorage.app',
    measurementId: 'G-JWJJ702QBD',
    databaseURL: 'https://to-do-list-app-270f5-default-rtdb.firebaseio.com/',
  );
}
